# Project: GeneticLib
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ValueEncodedMutationStrategy.o Chromosome.o ValueEncodedChromosome.o SinglePointCrossoverStrategy.o SelectionStrategy.o RouletteWheelSelectionStrategy.o MutationStrategy.o Individual.o GeneticAlgorithm.o CrossoverStrategy.o MultiplePointCrossoverStrategy.o $(RES)
LINKOBJ  = ValueEncodedMutationStrategy.o Chromosome.o ValueEncodedChromosome.o SinglePointCrossoverStrategy.o SelectionStrategy.o RouletteWheelSelectionStrategy.o MutationStrategy.o Individual.o GeneticAlgorithm.o CrossoverStrategy.o MultiplePointCrossoverStrategy.o $(RES)
LIBS =  -L"lib"  
INCS =  -I"include"  -I"F:/Home/knoppix/code/cc/Logger"  -I"F:/Home/knoppix/code/cc/Matc"  -I"F:/Home/knoppix/code/cc/Miscellaneous" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"F:/Home/knoppix/code/cc/Logger"  -I"F:/Home/knoppix/code/cc/Matc"  -I"F:/Home/knoppix/code/cc/Miscellaneous" 
BIN  = GeneticLib.a
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before GeneticLib.a all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	ar r $(BIN) $(LINKOBJ)
	ranlib $(BIN)

ValueEncodedMutationStrategy.o: ValueEncodedMutationStrategy.cpp
	$(CPP) -c ValueEncodedMutationStrategy.cpp -o ValueEncodedMutationStrategy.o $(CXXFLAGS)

Chromosome.o: Chromosome.cpp
	$(CPP) -c Chromosome.cpp -o Chromosome.o $(CXXFLAGS)

ValueEncodedChromosome.o: ValueEncodedChromosome.cpp
	$(CPP) -c ValueEncodedChromosome.cpp -o ValueEncodedChromosome.o $(CXXFLAGS)

SinglePointCrossoverStrategy.o: SinglePointCrossoverStrategy.cpp
	$(CPP) -c SinglePointCrossoverStrategy.cpp -o SinglePointCrossoverStrategy.o $(CXXFLAGS)

SelectionStrategy.o: SelectionStrategy.cpp
	$(CPP) -c SelectionStrategy.cpp -o SelectionStrategy.o $(CXXFLAGS)

RouletteWheelSelectionStrategy.o: RouletteWheelSelectionStrategy.cpp
	$(CPP) -c RouletteWheelSelectionStrategy.cpp -o RouletteWheelSelectionStrategy.o $(CXXFLAGS)

MutationStrategy.o: MutationStrategy.cpp
	$(CPP) -c MutationStrategy.cpp -o MutationStrategy.o $(CXXFLAGS)

Individual.o: Individual.cpp
	$(CPP) -c Individual.cpp -o Individual.o $(CXXFLAGS)

GeneticAlgorithm.o: GeneticAlgorithm.cpp
	$(CPP) -c GeneticAlgorithm.cpp -o GeneticAlgorithm.o $(CXXFLAGS)

CrossoverStrategy.o: CrossoverStrategy.cpp
	$(CPP) -c CrossoverStrategy.cpp -o CrossoverStrategy.o $(CXXFLAGS)

MultiplePointCrossoverStrategy.o: MultiplePointCrossoverStrategy.cpp
	$(CPP) -c MultiplePointCrossoverStrategy.cpp -o MultiplePointCrossoverStrategy.o $(CXXFLAGS)
