# Project: GeneticNetTest
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"lib" GeneticNetLib.a ../Net/NeuralNetLib.a ../Logger/libLogger.a ../Miscellaneous/libMisc.a ../Matc/MatcLib.a ../Genetic/GeneticLib.a  
INCS =  -I"include"  -I"F:/Home/knoppix/code/cc/Genetic"  -I"F:/Home/knoppix/code/cc/Logger"  -I"F:/Home/knoppix/code/cc/Matc"  -I"F:/Home/knoppix/code/cc/Miscellaneous"  -I"F:/Home/knoppix/code/cc/Net" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"F:/Home/knoppix/code/cc/Genetic"  -I"F:/Home/knoppix/code/cc/Logger"  -I"F:/Home/knoppix/code/cc/Matc"  -I"F:/Home/knoppix/code/cc/Miscellaneous"  -I"F:/Home/knoppix/code/cc/Net" 
BIN  = GeneticNetTest.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before GeneticNetTest.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "GeneticNetTest.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
