/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class linkparser_SentenceParser */

#ifndef _Included_linkparser_SentenceParser
#define _Included_linkparser_SentenceParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     linkparser_SentenceParser
 * Method:    parseSentence
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_linkparser_SentenceParser_parseSentence
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     linkparser_SentenceParser
 * Method:    parseConversation
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_linkparser_SentenceParser_parseConversation
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
